### ISSUE TITLE
`set_volume` doesn't work for more than one added sounds

### ISSUE THREAD

**Issue by kyoobey** [Rodrigodd/audio-engine#4]
i think i discovered a bug. the volume field of more than 1 sound is completely ignored.
i went ahead and fixed it, you can check out my fork's `volume-fix` branch (https://github.com/tshrpl/audio-engine_by_Rodrigodd/tree/volume-fix), there's an example `multiple_tracks` demonstrating this issue

**Comment by Rodrigodd** [comment]
Fixed by #5
