### ISSUE TITLE
Put OGG and WAV support behind features

### ISSUE THREAD

**Issue by mattfbacon** [Rodrigodd/audio-engine#6]
Some users may not want or need these features. As such, allow them to be disabled through Cargo features.

**Comment by Rodrigodd** [comment]
Implemented that here 8d62f5884aec8874b8a09d7bcb04960a6bc0be1a.

See if it is good for you.

**Comment by mattfbacon** [comment]
Looks good to me. Thanks. Can you make a new Cargo release?

**Comment by Rodrigodd** [comment]
Done.
