### ISSUE TITLE
`stop` does nothing on sounds set to loop 

### ISSUE THREAD

**Issue by mattfbacon** [Rodrigodd/audio-engine#7]
If a sound is set to loop with `set_loop(true)`, calling `stop()` and/or `reset()` on it does nothing.

**Comment by Rodrigodd** [comment]
I reproduce and implement this fix 78e50e47ea81b0c74d92626c00b1b45b689c7ded. But I could not reproduce exactly what you have reported.

That fix was only about `stop()` not working (was acting as a `reset()`) when all sounds were playing, but didn't involve `set_loop()`.

Can you check if that solved your issue? If not, can you give me a better reproduction steps? A code snippet would be ideal.

The issue that I fixed was reproducible by this code:

```rust
use audio_engine::{AudioEngine, OggDecoder};
use std::io::Cursor;

fn main() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("debug")).init();

    let engine = AudioEngine::new().unwrap();
    let mut music = engine
        .new_sound(OggDecoder::new(Cursor::new(&include_bytes!("pipe.ogg")[..])).unwrap())
        .unwrap();

    println!("playing");
    music.play();

    std::thread::sleep(std::time::Duration::from_secs(2));
    println!("stop");
    music.stop();

    std::thread::sleep(std::time::Duration::from_secs(2));
    println!("playing");
    music.play();

    std::thread::sleep(std::time::Duration::from_secs(2));
    println!("reset");
    music.reset();

    std::thread::sleep(std::time::Duration::from_secs(2));
    println!("quit");
}
```

**Comment by mattfbacon** [comment]
Oh, maybe `stop` didn't work at all? I didn't stop anything other than a sound that I had looping so I assumed that that was the issue but it may be that it didn't work at all.

**Comment by mattfbacon** [comment]
Yes, your fix works. Cargo release?

**Comment by Rodrigodd** [comment]
Done.
